Dd 1335
DANS-KNAW/dans-datastation-tools pull request #27
Opened 2023-04-05 15:25 UTC by ericdevries

Fixes DD-1335

# Description of changes

Cleanup of notifications after a certain amount of days. 

What this also shows is my idea for wrapping the postgres stuff inside some class that just lets us use it without dealing with the terrible psycopg API. I believe this is the right level of abstraction here, in the context of this project. 

If we were to write unit tests for this, it would be tricky because of the direct usage of the psycopg objects in the logic, but abstracting that away will probably make the code too complex, just for the sake of "clean code". 

If you disagree with my opinion, do not hesitate to let me know :).

Also on code formatting, I formatted this with "black" (see https://pypi.org/project/black/) to get rid of custom formatting. I find it very pleasing to look at as every python code will look identical. 

# How to test

# Related PRs

(Add links)

*

# Notify

@DANS-KNAW/dataversedans

2023-04-06 09:25 UTC, PaulBoon commented
About the formatting (black); When using PyCharm I don't remember feeling the need to reformat. Could this 'black' be integrated in PyCharm or in the build process somehow not having me to think about it?

2023-05-24 14:04 UTC, janvanmansum requested changes
@ericdevries : I have restructured the project. Please refactor this PR to conform to the new style. 

See also: https://dans-knaw.github.io/dans-datastation-tools/dev/

If it is more convenient you might also do  new PR.

2023-05-24 14:13 UTC, ericdevries commented
> About the formatting (black); When using PyCharm I don't remember feeling the need to reformat. Could this 'black' be integrated in PyCharm or in the build process somehow not having me to think about it?

I don't use pycharm, but I know it is properly supported in Vim and visual studio code. It looks a bit more cumbersome for IntelliJ products though.

2023-05-24 14:21 UTC, ericdevries commented
Also seeing as the development guidelines state that the PyCharm formatter should be used, perhaps we should not go down the black route anymore. 

My only problem is that I don't use pycharm

2023-05-30 13:09 UTC, janvanmansum commented on src/datastation/dv_notifications_cleanup.py
> +def positive_int(value):
Move to `utils` package

2023-05-30 13:13 UTC, janvanmansum commented on src/datastation/dataverse/notifications.py
> +    """Imports users from a CSV file into a Dataverse instance. The CSV file can be exported from EASY or manually
Remove the doc comment (copy-paste error?)

2023-06-02 12:24 UTC, janvanmansum approved these changes

2023-06-02 12:24 UTC, merged