DD-1637 Add age option to deposit-createreport script
DANS-KNAW/dans-datastation-tools pull request #66
Opened 2024-09-10 13:28 UTC by aliassheikh

Fixes DD-1637 age optie voor deposit-create-report

# Description of changes
added to `~/git/dans-core-systems/modules/dans-datastation-tools/src/datastation/deposit_create_report.py`
`add_argument('-a', '--age', dest='age', help='the number of days before today ')` 
When it is given in the command line, it will set the startdate argument to asked date, if it is an integer,

# How to test
For example, in vagrant ssh:
`python3  /vagrant/modules/dans-datastation-tools/src/datastation/deposit_create_report.py --help`
# Related PRs

(Add links)

*

# Notify

@DANS-KNAW/core-systems

2024-09-10 13:37 UTC, jo-pol commented on src/datastation/deposit_create_report.py
> +    group.add_argument('-a', '--age', dest='age', help='the number of days before today ')
```suggestion
    group.add_argument('-a', '--age', dest='age', help='Filter from record creation not older than a number of days before today ')
```

2024-09-16 07:43 UTC, janvanmansum commented on src/datastation/deposit_create_report.py
> +    if args.age is not None and str(args.age).isnumeric(): # Note: args is a Namespace object
You can just tell argparse it should be in an int at line 54.

2024-09-16 07:44 UTC, janvanmansum commented on src/datastation/deposit_create_report.py
> +    group.add_argument('-a', '--age', dest='age', help='Filter from record creation not older than a number of days before today ')
```suggestion
    group.add_argument('-a', '--age', dest='age', type=int,  help='Filter from record creation not older than a number of days before today ')
```

2024-09-16 07:45 UTC, janvanmansum requested changes

2024-09-16 07:45 UTC, janvanmansum commented on src/datastation/deposit_create_report.py
> +    if args.age is not None and str(args.age).isnumeric(): # Note: args is a Namespace object
See: https://docs.python.org/3/library/argparse.html#example

2024-09-24 14:34 UTC, merged