DD-1072: cleanup python scripts
DANS-KNAW/dans-datastation-tools pull request #9
Opened 2022-08-08 11:02 UTC by lindareijnhoudt

Fixes DD-1072

# Description of changes

   * WIP replace_metadata_field_values
   * Check reindex_datasets, use similar argument names
   * Check delete_role_assignments
   * no defaults for required args
   * Check dv-delete-draft-datasets
   * Check convert_dataset_metadatafiles; TODO convert

# How to test

# Related PRs

(Add links)

*

# Notify

@DANS-KNAW/dataversedans

2022-08-23 13:07 UTC, PaulBoon commented on src/datastation/scripts/retrieve_dataset_pids.py
> +    parser.add_argument('-o', '--output-dir', default='.', dest='output_dir',
output dir now defaults to '.', the working dir, but previously it was the configured dir now in 'files_root'. I have open an issue for this last config change (DD-1083). Maybe we can get rid of that issue and fix it here, if we want to?

2022-08-23 13:15 UTC, PaulBoon commented on src/datastation/scripts/unlock_datasets.py
> +    unlock_dataset_command(config['dataverse']['server_url'], config['dataverse']['api_token'], args.pids_file)
Indeed better to move these 'defaults' close to the input parsing.

2022-08-24 12:40 UTC, janvanmansum commented
I did the following test on `dev_archaeology`: 

```
poetry run dv-replace-metadata-field-values -m citation -n title -f 'Manual Test' -t 'Changed title' -p 'doi:10.5072/FK2/PAGIFD'
2022-08-24 02:38:33 : DEBUG : init : Initialized logging
2022-08-24 02:38:34 : DEBUG : replace_metadata_field_value_action : doi:10.5072/FK2/PAGIFD: Found title with value Manual Test
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/janm/git/service/dataverse-dans/dans-datastation-tools/src/datastation/scripts/replace_metadata_field_values.py", line 102, in main
    replace_metadata_field_value_action(server_url, api_token, args.pid, args.mdb_name, args.field_name,
  File "/Users/janm/git/service/dataverse-dans/dans-datastation-tools/src/datastation/scripts/replace_metadata_field_values.py", line 52, in replace_metadata_field_value_action
    updated_field['value'][index_replace_from] = replace_to
TypeError: 'str' object does not support item assignment
```

2022-08-24 12:45 UTC, janvanmansum reviewed
* In the help strings make the option name and placeholder use the same term, e.g. instead of `-d PIDS` use `-d DATASETS`.

2022-08-24 12:54 UTC, janvanmansum reviewed
At some point, not necessarily now, we should probably create some naming conventions for the scripts, as there are going to be many of them. How about:
```
dv-<object>-<action>, e.g.,

dv-dataset-<action>, e.g.,
dv-dataset-publish
dv-dataset-replace-metadata-field

dv-user-<action>, e.g.,
dv-user-import
```
I am using the singular for the object assuming that every command supports operating both on a single object as well as on a list of objects.

2022-08-31 07:42 UTC, lindareijnhoudt commented on src/datastation/scripts/oai_harvest.py
> +    parser.add_argument('-s', '--set', default='', help='The PMH recordset to be harvested.')
it seems we haven't configured the sets in the Data Station

2022-08-31 08:59 UTC, janvanmansum requested changes
Remove `convert_dataset_metadatafiles.py`.

2022-08-31 09:03 UTC, janvanmansum requested changes
* Remove output_file argument from batch_process

2022-08-31 09:31 UTC, janvanmansum requested changes

2022-08-31 09:31 UTC, janvanmansum commented on src/datastation/scripts/oai_harvest.py
logging instead of prints

2022-08-31 09:31 UTC, janvanmansum commented on src/datastation/scripts/replace_metadata_field_values.py
>  def replace_metadata_field_value_action(server_url, api_token, pid, mdb_name, field_name, field_from_value,
```suggestion
def replace_metadata_field_value(server_url, api_token, pid, mdb_name, field_name, field_from_value,
```

2022-08-31 09:31 UTC, janvanmansum commented on src/datastation/scripts/replace_metadata_field_values.py
> +    parser.add_argument("-m", "--metadata-block", help="Name of the metadata block", dest="mdb_name")
Remove? Not used?

2022-08-31 11:19 UTC, merged